/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 20-maj-2022 12:45:04 				*/
/*  DBMS       : Oracle 						*/
/* ---------------------------------------------------- */
 

/* Create Tables */

CREATE TABLE  main.client
(
	client_id NUMBER(8) NOT NULL,
	email VARCHAR2(100) NOT NULL,
	CONSTRAINT pk_client PRIMARY KEY (client_id),
	CONSTRAINT email_unq UNIQUE (email) USING INDEX
);

CREATE TABLE  main.destination
(
	destination_id NUMBER(8) NOT NULL,
	country_iso_id CHAR(2) NOT NULL,
	name VARCHAR2(255) NOT NULL,
	CONSTRAINT pk_destination PRIMARY KEY (destination_id),
	CONSTRAINT name_unq UNIQUE (country_iso_id,name) USING INDEX,
	CONSTRAINT country_id_chk CHECK ()
);

CREATE TABLE  main.offer
(
	offer_id NUMBER(8) NOT NULL,
	type_id NUMBER(8) NOT NULL,
	name VARCHAR2(255) NOT NULL,
	price NUMBER(8,2) NOT NULL,
	child_price NUMBER(8,2) NULL,
	minimal_price NUMBER(8,2) NOT NULL,
	departure_date DATE NOT NULL,
	comeback_date DATE NOT NULL,
	destination_id NUMBER(8) NOT NULL,
	duration INTERVAL DAY(2) TO SECOND(6) NOT NULL,
	start_offer_date DATE NOT NULL,
	end_offer_date DATE NOT NULL,
	picture BLOB NULL,
	max_paparticipants NUMBER(8) NOT NULL,
	has_free_spots CHAR(1) NOT NULL,
	CONSTRAINT pk_offer PRIMARY KEY (offer_id),
	CONSTRAINT price_chk CHECK (price >= minimal_price),
	CONSTRAINT child_price_chk CHECK (child_price >= minimal_price),
	CONSTRAINT comback_date_chk CHECK (comeback_date > departure_date),
	CONSTRAINT end_offer_chk CHECK (end_offer_date > start_offer_date),
	CONSTRAINT fk_offer_destination FOREIGN KEY (destination_id) REFERENCES  main.destination (destination_id) ON DELETE Cascade,
	CONSTRAINT fk_offer_offer_type FOREIGN KEY (type_id) REFERENCES  main.offer_type (type_id) ON DELETE Cascade
);

CREATE INDEX offer_available_idx   
 ON  main.offer (has_free_spots);

CREATE TABLE  main.offer_type
(
	type_id NUMBER(8) NOT NULL,
	name VARCHAR2(255) NOT NULL,
	CONSTRAINT pk_offer_type PRIMARY KEY (type_id),
	CONSTRAINT name_unq UNIQUE (name) USING INDEX
);

CREATE TABLE  main.reservation
(
	client_id NUMBER(8) NOT NULL,
	offer_id NUMBER(8) NOT NULL,
	creation_datetime TIMESTAMP(6) NOT NULL,
	participants_num NUMBER(8) NOT NULL,
	price NUMBER(8,2) NOT NULL,
	CONSTRAINT pk_reservation PRIMARY KEY (client_id,offer_id),
	CONSTRAINT participants_num_chk CHECK (participants_num >= 1),
	CONSTRAINT FK_reservation_client FOREIGN KEY (client_id) REFERENCES  main.client (client_id) ON DELETE Cascade,
	CONSTRAINT FK_reservation_offer FOREIGN KEY (offer_id) REFERENCES  main.offer (offer_id) ON DELETE Cascade
);